Include sys/types.h for ssize_t on OS/2
This fixes the following error,

In file included from ../../../include/vlc_stream.h:27,
                 from ../../../include/vlc_demux.h:33,
                 from mkv.hpp:55,
                 from demux.hpp:28,
                 from virtual_segment.cpp:27:
../../../include/vlc_block.h:138: error: 'ssize_t' has not been declared

Signed-off-by: Rémi Denis-Courmont <remi@remlab.net>
(cherry picked from commit 248812582798e57d8da527095fe29d4b3df75ad4)

Signed-off-by: Jean-Baptiste Kempf <jb@videolan.org>